### PR TITLE
Update figure results

### PR DESCRIPTION
**Pull request by gwaybio**
Adding PNG code and updated PNG figure.

This PR is mainly to test the continuous analysis implementation from #2. My strategy here is:

1. Make changes on my forked repo or in a branch that is not called staging or master
2. Make a pull request to commit into the greenelab `staging` branch
3. This should kick off a drone run and commit these changes back into the greenelab `master` branch

@dhimmel @brettbj @cgreene does this seem like the way to implement continuous analysis with a pull request model?

### CODE REVIEW

**Comment by dhimmel** [comment]
To see how this works can you reset `figures/boxplot_validation_TCGA_summary.png` in this pull request. So your pull request only changes the code and we make sure CI is actually updating the image?

**Comment by cgreene** [comment]
Those three steps seem correct to me. Number 1 could be "on my forked repo or in a branch that is not called `staging` or `master` if you wanted it to be."

**Comment by cgreene** [comment]
I agree with @dhimmel on removing figures and checking to see that CI generates them.

**Comment by gwaybio** [comment]
> can you reset figures/boxplot_validation_TCGA_summary.png

sounds good. Removed

>  on my forked repo or in a branch that is not called staging or master

yep! edited

**Review by dhimmel — APPROVED** [review]

**Review by cgreene — APPROVED** [review]

**Comment by gwaybio** [comment]
ok here goes

**Comment by cgreene** [comment]
:drum_roll: (🥁) should be here

**Pull request merged**
